# Generated by Django 5.2.4 on 2025-07-28 08:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("HW", "Hardware"), ("SW", "Software")],
                        default="HW",
                        max_length=2,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("purchase_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Enter a valid email address."
                            )
                        ],
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("IT", "Information Technology"),
                            ("HR", "Human Resources"),
                            ("FIN", "Finance"),
                            ("MKT", "Marketing"),
                            ("OPS", "Operations"),
                        ],
                        default="IT",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetAssignmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_on", models.DateTimeField(auto_now_add=True)),
                ("returned_on", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_logs",
                        to="db.asset",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_assignments",
                        to="db.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Assignment Log",
                "verbose_name_plural": "Asset Assignment Logs",
                "ordering": ["-assigned_on"],
                "get_latest_by": "assigned_on",
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="db.employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("serial_number__isnull", False)),
                fields=("serial_number",),
                name="unique_serial_number",
            ),
        ),
    ]
